### ISSUE TITLE
Add iptables API

### ISSUE THREAD

**Issue by andrewrynhard** [siderolabs/talos#1417]
The ability to inspect iptables could be useful.

**Comment by elreydetoda** [comment]
So, would this feature also be able to block the exposed ports in the picture below?  From my understanding of [this](https://www.talos.dev/docs/v0.14/guides/configuring-network-connectivity/) those ports aren't necessary to expose to the local network. ( all the "Local Address:Port" that don't have 127.0.0.1 except the 50000 port )

![image](https://user-images.githubusercontent.com/10230166/151682907-32b32d35-b1e7-46a0-ab35-24e8346736b9.png)


I don't know if maybe this is just a shortcut since I used the [Talos in QEMU on your laptop](https://youtu.be/UzQ8Hl_TfF8) YT video, and the QEMU provisioner just exposes it since it's more of a _dev_ environment. I haven't run a normal install from the ISO yet, but I was just curious because I wanted to lock down network access from as much as I can. I'm sure most of them probably require certs or some type of cert auth, but just being able to prevent access to it at all would help ease my mind knowing people can't even touch the ports so they wouldn't be able to access/exploit services on there.

extra debug info:
talosctl: v0.14.1
kernel: v0.14.1
initramfs: v0.14.1
node type: worker node
command ran: `sudo -E talosctl cluster create --provisioner qemu --masters 3 --workers 1 --memory 4096 --nameservers="<redacted>" --with-kubespan=true`

**Comment by smira** [comment]
yes, our plan is to implement #4421 to support control over the exposed ports

**Comment by elreydetoda** [comment]
> yes, our plan is to implement #4421 to support control over the exposed ports

Awesome! Glad to you know you all are already thinking ahead :grin: :partying_face:

**Comment by smira** [comment]
Fixed via #4421
