### ISSUE TITLE
Enable multipath

### ISSUE THREAD

**Issue by DaveJWSmith** [siderolabs/talos#3204]
Feature request:
Enable multipath in talos to allow access to SAN disks

**Comment by Ulexus** [comment]
@DaveJWSmith Are you referring to NVME, MD, or DM... or something else?  This is also not likely to be in isolation, but will require additional kernel modules and possibly userspace setup.  Can you give some more detail on your needs?

**Comment by DaveJWSmith** [comment]
@Ulexus, We are trying to enable connection of nodes to a fibre channel SAN using multipath.   I had some comms with Andrew Rynhard about it, he felt it was a valid use case but, like you, felt it would probably require both kernel modules and userspace setup.

Background: We are using an HP C7000 Blade Centre with 16 blades, each with 2x146GB drives.   This had been setup as a single RAID device.   Initially we had hoped to be able to boot using a partition of the disk, to allow us to use the rest for ceph/rook storage.   We rapidly understood this was not the Talos paradigm.   We have now split the RAID, meaning we are using 1 of the disks for Talos, and the other is available for ceph/rook.   This is not ideal, we have a significantly over spec disk for Talos, and not much storage for ceph/rook.   Our thinking hade been to create the boot disk on our Fibre Channel storage for Talos, leaving both local disks available for ceph/rook, this is when we found multipath was not yet included.

I'm not sure I have adequately answered your question.   Please feel free to ask for more information.   My colleague who is available from Tuesday may also be able to help more.

**Comment by Ulexus** [comment]
I follow now, yes.

It looks like that system is built on `DM_MULTIPATH`, which means yes:  it will require both kernel support (easy) and userspace support (hard).

This class of problems comes down to our need to get the Talos "plugins" system added.  We can get the kernel module turned on pretty easily, but as of right now, we have no way of running arbitrary userland daemons outside of Kubernetes.  

This is even worse in light of the fact that you want to use it effectively as a root device, because that means that the logic must be in the initrd.  By design, Talos' initrd is completely generic, extremely small, and confguration-free.

One option is for you to run Talos purely in RAM with netboot.  This isn't a good idea for the controlplane, but it is fine for worker nodes.  Another option is to add some cheap disk-on-modules or USB sticks for Talos to use.  

The two main things which Talos uses which would be performance-affecting are:
 - container image cache
 - container logs

Of note, Talos's rootfs always runs in RAM anyway.  The only things the disk is used for on worker nodes is:
 - container image cache
 - container logs
 - configuration cache
 - bootloader
 - kernel and initrd storage
