### ISSUE TITLE
Secure maintenance mode

### ISSUE THREAD

**Issue by sergelogvinov** [siderolabs/talos#4214]
To protect the server we need to improve the maintenance mode.

Which cases we need maintenance mode:
* in first boot time
* make some works on the node (format partitions, define the hardware errors) 

We can define the special machine type like we have for worker/contalplane
Minimal config requirements:

```yaml
version: v1alpha1
machine:
    type: maintenance
    ca:
        crt: BASE64-CA
```

In this case 
* the server will trust only requests signed with that CA-cert. 
* can store in cloud user-data this insensitive machine config, and after creating an instance put the controlplane/worker config securely. 
* after good installation the server switches on the flag in META, which disables maintenance mode without machine config. If someone drop/delete the machine config and reboot the server, it does not switch to unprotected maintenance mode.

If something bad happened with the node, we we can set/redefine grub-boot mode manually
```
talos.platform=maintenance
```

**Comment by sergelogvinov** [comment]
The problem here - how client can verify the server.

Talos can add verify challenge in the protocol.

Client send random string, server signs it using the local key. Key can be string ssh-public-key (most of cloud providers support it). Or some addition key from machine config. 

In this case only cloud provider can hack you. But it can do it without man-in-the-middle attack.

**Comment by smira** [comment]
Signing requires private key (not public key), and verification happens using public-key.

So I don't think it's that simple, but certainly the problem is there, and it's better to avoid using user data.

One of the easy ways for the cloud would be in fact to send some token via user-data which would authenticate client-server connection. As token is temporary and only used to run maintenance mode, it might be not that bad?
