### ISSUE TITLE
disks API should report `by-id` and `by-path` links

### ISSUE THREAD

**Issue by Ulexus** [siderolabs/talos#4472]
## Feature Request

When constructing machine configs for reliable installation media selection, it is useful to use the `/dev/disk/by-id` or `/dev/disk/by-path` links.  However, the current `disks` API makes these difficult to determine (especially since `talosctl ls --insecure` is not supported).

To facilitate this, we should include link information for the `by-id` and `by-path` paths for these.  In doing so, note that the `by-id` link references are multi-valued: more than one link exists for the same disk:

```
$ ls /dev/disk/by-id -l |grep nvme0n1 |grep -v nvme0n1p
lrwxrwxrwx 1 root root 13 Oct 20 21:04 nvme-eui.002538570141e6e2 -> ../../nvme0n1
lrwxrwxrwx 1 root root 13 Oct 20 21:04 nvme-Samsung_SSD_970_EVO_1TB_S5H9NS0N703046B -> ../../nvme0n1
```

**Comment by Ulexus** [comment]
Perhaps something like:

```protobuf
message Disk {
  ...
  // Aliases, such as `/dev/disk/by-id/nvme-eui.002538570141e6e2`
  repeated string aliases = 10
}
```

**Comment by iMartyn** [comment]
In case anyone is coming here wanting this and they are not still in the build phase, `talosctl ls /dev/disk/by-id` works once the machine is joined to the cluster.  Won't help for install disk situations, but might for extra disk scenarios.  Would love to see this implemented in `talosctl disks` in future.

**Comment by techguydave** [comment]
Thank you Martyn, I was pulling my hair out over this! This should be mentioned somewhere in the docs.

**Comment by iMartyn** [comment]
/cc @rothgar  This is the issue you asked me to open on slack, perhaps it could be reopened and reassessed?  As mentioned, when you most need `talosctl disks` to work is during the build phase, linux provides no guarantee that `/dev/sdX` is consistent and so at the moment you have to set up machines in a two-phase basis if you want to use consistent disk naming with talos.  First, add machine, then use `talosctl list`, then add the disks, instead of a single provision.  Most often triggered if booting from a USB device, but some machines will have a random disk order every boot.

**Comment by rothgar** [comment]
Thanks for the mention. We're still working on improvements for disk management and this will likely be improved as we progress on #8367 

We need to fix some of the other known limitations first but this will probably be handled natively by the Talos API in the future.
