### ISSUE TITLE
Kubespan - 'Kubernetes annotation based' expiry 

### ISSUE THREAD

**Issue by moonrockfamily** [siderolabs/talos#4562]
## Feature Request
When a machine dies and you want to create a new machine to host the same workload (same machine config), including IP address, you may encounter the warning "peer address overlap" and also notice its failure to communicate with other peers.

Failure to delete the node from Kubernetes is the root cause of this warning and failure to communicate.

### Description
It would be nice if the KubeSpan peer registry (Kubernetes annotation based) would expire nodes such that old nodes don't prevent new/replacements from taking up the peer role with the same machine config, including the IP address!

**Comment by smira** [comment]
@moonrockfamily I think this is coming due to the discovery service. It has some TTL for the entries (currently 30 min), so it will report removed node for 30 mins before it gets removed. Kubernetes should be updated with new data, so it shouldn't be a problem. I think proper fix here would be to have a way to remove discovery data on node reset.

**Comment by moonrockfamily** [comment]
I like that solution better than expiry since the timeliness of recovery is operator controlled and tightly related with their recovery actions.

**Comment by Ulexus** [comment]
The problem in this case appears to _not_ be from the discovery service.  The issue is:
 - Node A with IP address 192.168.1.50 is a member of the cluster
 - Node A (machine) is reinstalled, obtains a new Node name:  Node B; however, IP address is the same
 - Node A (Kubernetes resource) still exists with KubeSpan annotations
 - Node B joins Kubernetes cluster such that both Node A and Node B Kubernetes resources exist, each marked up with KubeSpan annotations
 - KubeSpan sees two routes to the same IP (Node A and Node B), fails with overlap message

If, at this point, you manually delete Node A (Kubernetes resource), Node B is able to fully join KubeSpan.  Node A is not ever removed automatically, however, resulting in this issue.

My proposed fix is to add an additional KubeSpan Node Annotation on the order of `kubespan.talos.dev/last-update` with a timestamp of the last update.  This will enable most-recent matching for Kubernetes-based discovery like as we have for the discovery service.

@moonrockfamily , please correct if I am incorrect in my assumptions of the state.
