### ISSUE TITLE
Sponsored: APIs for debugging networking

### ISSUE THREAD

**Issue by andrewrynhard** [siderolabs/talos#4722]
### Description

APIs to do things like ping, dns lookup, traceroute would be something nice to have.

**Comment by sbskas** [comment]
Hum, how to you use and API for debugging network if the network is down ?

**Comment by smira** [comment]
I think this issue was more about providing tools to debug network, but certainly API connectivity is a requirement anyways. E.g. debugging issues which don't affect API connectivity.

**Comment by sbskas** [comment]
One proposal I made was to trigger network test when connectivity with peers is lost (gateway, dns, masters). Test which could be ran and displayed on the console in a loop.
The issue here is when there is a problem with network connectivity and you loose the access to API for whatever reason, you cannot identify the problem by looking at the console.
Error report may be gone for long on the console, or mixed up with other logs.

**Comment by SixFive7** [comment]
I really like the whole declarative + use the API stance. But the one and only thing I would add to any plan for an interactive console (https://github.com/talos-systems/talos/issues/4584) would be the possibility to change network settings. Even if it can only be used to set the live network settings without any useful persistence. It would help get the network on a node broken up enough to at least run `talosctl dmesg -n broken.node.com` and debug what happened to said network connectivity.

**Comment by smira** [comment]
there's also #4591 which should help to apply potentially disruptive changes
