### ISSUE TITLE
add STIG testing as part of our CI test suite

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#5061]
## Feature Request

See https://github.com/talos-systems/stig/tree/main/talos

### Description

We could probably add that to the one of the `e2e.sh` steps by checking out the STIG repo and calling some high-level script which runs all checks.

e.g.: https://github.com/talos-systems/talos/blob/7b33ffbd8558e92d6fcc5986d5985ac2560c261b/hack/test/e2e.sh#L215-L244

if the tests are quick enough, we could probably run them every time, or we could build a dedicated job for it

this is how e.g. extension tests are ran: https://github.com/talos-systems/talos/blob/7b33ffbd8558e92d6fcc5986d5985ac2560c261b/.drone.jsonnet#L361-L366

**Comment by Ulexus** [comment]
Yeah, all the checks are fast.  Running each time should not be a problem.
We just need to get the wrapper script in order, then.

**Comment by JAORMX** [comment]
I hadn't noticed the STIG repo, but you might also want to take a look at [ComplianceAsCode](https://github.com/ComplianceAsCode/content) in order to do compliance checks, I'm sure they'd be thrilled to get another OS in there. A STIG profile would look as follows: https://github.com/ComplianceAsCode/content/blob/master/products/rhel8/profiles/stig.profile

And there's already rules checking for kubernetes settings: https://github.com/ComplianceAsCode/content/blob/master/applications/openshift/kubelet/kubelet_configure_client_ca/rule.yml

Not to diminish the work that's been done, I see the scripts in the STIG repo are quite extensive; however, I thought folks might be interested in getting Talos compliance rules be part of an existing community. I'd be happy to give an overview to folks if interested.
