### ISSUE TITLE
sysctls for I/O performance

### ISSUE THREAD

**Issue by Ulexus** [siderolabs/talos#5175]
## Feature Request

In testing heavy I/O loads with Ceph, a couple sysctls came up which should probably be bumped by default.  We already bumped inotify recently, but it seems a bit more may be in order.

`fs.aio-max-nr` = 1048576
`fs.inotify.max_user_instances` = 8192

**Comment by DmitriyMV** [comment]
So a bit of a background: aio for example, is used by Ceph and Veritas, who [recommends](https://sort.veritas.com/public/documents/HSO/2.0/linux/productguides/html/hfo_admin_ubuntu/ch04s03.htm) setting aio-max-nr to `1048576`. And since we want to have "good defaults" - this is probably a good idea to set to "big enough value".

`fs.inotify.max_user_instances` unlike `fs.inotify.max_user_watches` is not set [dynamically](https://www.kernel.org/doc/Documentation/sysctl/fs.txt) which is why we want to increase it to 8192 (default is usually 512, which is a small number.)
