### ISSUE TITLE
talos install image is v0.14.3 but it does not exist

### ISSUE THREAD

**Issue by nmattela** [siderolabs/talos#5182]
### Description
In the generated controlplane.yaml and worker.yaml, image `ghcr.io/talos-systems/installer:v0.14.3` is specified for the talos installer, yet it does not exist (see https://github.com/orgs/talos-systems/packages/container/installer/versions). I suppose there was just a mixup between the Talos version and the Talos installer version :)

### Logs 
```
failed to pull image "ghcr.io/talos-systems/installer:v0.14.3": failed to resolve reference "ghcr.io/talos-systems/installer:v0.14.3": ghcr.io/talos-systems/installer:v0.14.3: not found
```

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
```
Client:
	Tag:         v0.14.3
	SHA:         73f4efd7b53baac12709281552f4eed7b47bfc1e
	Built:       
	Go version:  go1.18
	OS/Arch:     linux/amd64
Server:
```
- Kubernetes version: [`kubectl version --short`]
Can't check as I haven't managed to successfully install Talos and gain access to a command prompt
- Platform:
Talos Linux

**Comment by TimJones** [comment]
This is due to our recent GitHub organisation name change. We are working with GitHub to recover the images under the `talos-systems` name. In the mean time, you can work around this by editing the `controlplane.yaml` and `worker.yaml` files and replacing references to `ghcr.io/talos-systems` to `ghcr.io/siderolabs`
