### ISSUE TITLE
Build and Publish Talos images for KubeVirt / Harvester / OpenShift Virtualization 

### ISSUE THREAD

**Issue by usrbinkat** [siderolabs/talos#5780]
## Feature Request
Requesting official images for kubevirt based hosting platforms.

### Description
Kubevirt is gaining ground with a growing [adopters list](https://github.com/kubevirt/kubevirt/blob/main/ADOPTERS.md) and commercialized platforms such as [Rancher's Harvester](https://rancher.com/products/harvester) and Red Hat's [OpenShift Virtualization](https://www.redhat.com/en/technologies/cloud-computing/openshift/virtualization) leading the way. Having a Sidero Labs Talos image officially built for this platform and published to a container registry for direct consumption would be a value add for the Talos community.

Images are trivially similar to OpenStack and ci build/test can be easily accommodated on kind kubernetes.

Kubevirt image CI testing examples:
* [gh actions step](https://github.com/ContainerCraft/kmi/blob/0b6dc6073d9edab5fd8cf51796638cffd0008ecb/.github/workflows/test.yml#L26)
* [run bats tests](https://github.com/ContainerCraft/kmi/blob/ccio/tests/run.bats)

#### Additional Information
* [Sidero Slack #support thread](https://taloscommunity.slack.com/archives/CMARMBC4E/p1655472618939939)

**Comment by usrbinkat** [comment]
I do not see value in publishing the ISO for kubevirt, I believe we can cross that off the list.

we're working on an alternate route to supplying vmlinuz + initramfs to kubevirt, stay tuned for that but they will be published to container registry as it's native file type, not based on "containerized" files, so I think this would be redundant effort and depricated in the future.

Can talos pickup the talos.config from a local filesystem supplied via NoCloud or cloud-config/cloud-init? If so, we can store the config as a k8s secret and mount it into the VM at runtime.

finally, if working towards having a Talos Cluster API integration on the Kubevirt CAPI Provider is on the map then I suspect the maintenance mode / instance API driven configuration model will be required?

**Comment by smira** [comment]
I think `nocloud` is kind of overcomplicated to work with, as it also covers networking configuration. 

It's not documented properly, but Talos can pick up machine config in `meta`l mode from a mounted blockdevice with a specific partition label.

So we could publish regular `metal` image with a `talos.config=` URL set so that Talos picks it up from the volume. I never used kubevirt myself, so I'm lost on the options available.

It's not clear from the kubevirt docs what are the actual formats of images supported via container images, unless I completely missed that part. 

We could also add `kubevirt` as a specific Talos platform and implement ways to get network and machine configuration which will work greate with kubevirt and kubevirt CAPI provider, but once again I need more details and pointers to the actual flows which work well with kubevirt.
