### ISSUE TITLE
Proxmox VM reboot with talos 1.1

### ISSUE THREAD

**Issue by lucacalcaterra** [siderolabs/talos#5797]
### Description
 reboot on proxmox vm
### Environment
Proxmox 

- Talos version: 1.1
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by sarandafl** [comment]
I have the same behavior:
Proxmox 7.2-5 attempting to run [talos-amd64.iso](https://github.com/siderolabs/talos/releases/download/v1.1.0/talos-amd64.iso). BIOS had to be changed from SeaBIOS to OVMF (UEFI) due to a reboot loop and error message: `Wrong EFI loader signature`.  VM was still stuck in a boot loop with the same message until the CPU type was changed from the default `kvm64` to host (`8 x Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (1 Socket)`) in my case.

**Comment by reitermarkus** [comment]
Using `host` prevents using live migration. Also, for me, switching to `host` did not immediately work since I had custom `args` in `/etc/pve/qemu-server/<vmid>.conf`:

```
args: -cpu kvm64,+ssse3,+sse4.1,+sse4.2
```

`kvm64` still works, but additional CPU features need to be enabled like this:

```
args: -cpu kvm64,+cx16,+lahf_lm,+popcnt,+sse3,+ssse3,+sse4.1,+sse4.2
```

**Comment by sauterp** [comment]
> > kvm64 still works, but additional CPU features need to be enabled like this:
> 
> @reitermarkus would you mind doing a PR to the docs?

You could extend on [this commit](https://github.com/siderolabs/talos/commit/a68a00f1b9bdbb519966bbf1ac7f463796a85abb). If you don't have time, I'm happy to do it also.
