### ISSUE TITLE
stable default hostname based on machine-id

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#5896]
Talos provides default hostname based on the IP address, e.g. `talos-192-168-1-1`. This hostname is not stable, as it changes with the IP address changes.

Proposal: replace it with the hostname based on stable ID, e.g. `machine-id` (32 chars): `talos-<machine-id>`. The benefit is that this hostname won't change unless the node is fully wiped.

**Comment by ohauer** [comment]
That's a nice idea!
I learned it the hard way with a different OS and also run in trouble with certs assigned to IP addresses as the other OS does ipconfig release during reboot.
Havent't looked what happens with talos and certs in case the IP change, but remember from the other solution nodes registerd twice with both IP's which leeds to several other issues, since then Im using only static IP over all nodes (even with my talos test cluster)

**Comment by smira** [comment]
Consider using shorter name by taking less characters, e.g. 6 chars a-z + 0.9: `36^6 = 2176782336`

**Comment by smira** [comment]
This should be disabled by default in the machine config, and enabled only for v1.2.0+ machine configs.

**Comment by smira** [comment]
thanks, good point on not exposing machine-id. I think if we take a part of machine-id, it should be fine as well, as exposing only 4 bytes out of 16 bytes should be non-identifying still. 

Also this hostname will change with node wipe, so if the node is reinstalled, it gets new machine-id and new default hostname.
