### ISSUE TITLE
talosctl as chocolatey package

### ISSUE THREAD

**Issue by FloMaetschke** [siderolabs/talos#6066]
## Feature Request
Since there is a windows-amd64 binary in your release, why not add it to chocolatey and update automatically each release?
It would make things easier. Kubernetes has a package, too. Its officially documented here:
https://kubernetes.io/docs/tasks/tools/install-kubectl-windows/#install-on-windows-using-chocolatey-or-scoop

Please add automatic chocolatey package creation for talosctl.

### Description

To setup a testcluster on windows:

choco install kubernetes-cli talos-cli  

or

choco install kubernetes-cli talosctl

and done.

**Comment by smira** [comment]
Please do that! more distributions channel is good!

**Comment by dedene** [comment]
@FloMaetschke I added talosctl to Chocolatey: https://community.chocolatey.org/packages/talosctl

@smira Currrenty the manifest lives in https://github.com/dedene/Chocolatey-Packages/tree/main/talosctl but if your team is willing to maintain this, I'm more than happy to transfer or share the ownership of the package. I'll be looking into automating releases so they closely follow the Talos releases, as otherwise there will be a risk it falls behind official releases. It references / downloads directly from the Github releases, so I think it's also something that easily could be automated and added to the Talos release pipeline.   What are your thoughts on this?

(I have a similar question for [scoop](https://github.com/siderolabs/talos/issues/5458) but the autoupdate functionality of scoop makes it less of a problem as long as the release structure - download links, filenames etc. - stays consistent)
