### ISSUE TITLE
talosctl bootstrap doesn't work on k8s 1.25.0+

### ISSUE THREAD

**Issue by githubcdr** [siderolabs/talos#6307]
## Bug Report

talosctl bootstrap command generates a PodSecurityPolicy that prevents the cluster from getting deployed correctly

### Description

```
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
  creationTimestamp: "2022-09-20T15:53:48Z"
  name: privileged
  resourceVersion: "256"
  uid: cc1cb65a-3493-4f7b-ac5a-6d6729162f92
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:

```
### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform:

**Comment by smira** [comment]
`talosctl bootstrap` doesn't generate any machine configuration.

Machine config is generated with `talosctl gen config` or via something using Talos libraries (e.g. CABPT). 

Talos machine configuration generation process disables PodSecurityPolicy for a long time (since v1.0.x), so your machine configuration is outdated.

**Comment by githubcdr** [comment]
Hi Smira,

Thanks, my bad that was the issue!
