### ISSUE TITLE
talosctl reboot doesn't properly wait for the node to be back

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#6460]
## Feature Request

From the tests:

```
=== RUN   TestIntegration/cli.RebootSuite
=== RUN   TestIntegration/cli.RebootSuite/TestReboot
    run.go:143: Running "/drone/src/_out/talosctl-linux-amd64 --talosconfig /tmp/e2e/qemu/talosconfig reboot -n 172.20.1.4,172.20.1.5 --debug"
=== RUN   TestIntegration/cli.RestartSuite
=== RUN   TestIntegration/cli.RestartSuite/TestSystem
    run.go:143: Running "/drone/src/_out/talosctl-linux-amd64 --talosconfig /tmp/e2e/qemu/talosconfig restart -n 172.20.1.4 trustd"
    run.go:205: 
        	Error Trace:	/drone/src/run.go:205
        	            				/drone/src/cli.go:112
        	            				/drone/src/restart.go:37
        	Error:      	Received unexpected error:
        	            	exit status 1
        	Test:       	TestIntegration/cli.RestartSuite/TestSystem
        	Messages:   	command failed, stdout: "", stderr: "error restarting process: 1 error occurred:\n\t* 172.20.1.4: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing dial tcp 172.20.1.4:50000: connect: connection refused\"\n\n\n"
```

Looking into the logs, 172.20.1.4 was rebooting when `TestIntegration/cli.RestartSuite/TestSystem` started, so previous reboot command either failed without proper exit code, or it hasn't performed proper waiting. Either is a bug.

**Comment by smira** [comment]
another case: CLI hangs for 5 hours (we need a deadline?)

https://ci.dev.talos-systems.io/siderolabs/talos/30025/2/5

![image](https://user-images.githubusercontent.com/55211/199454520-e164b169-1e4a-4429-abad-85ff80cfc25c.png)

**Comment by utkuozdemir** [comment]
Yes, deadline is needed for sure. I couldn't reproduce the actual issue though - any ideas?

**Comment by smira** [comment]
I don't have any specific ideas here, you can look for failures of cron CI runs and try to dig into server logs. My guess it's all about some bugs in handling API responses, but no idea for real. Probably it makes sense to go over the implementation, simplify it, apply unit-testing when possible, etc.

**Comment by utkuozdemir** [comment]
This PR partly addresses this: https://github.com/siderolabs/talos/pull/6485#issue-1442246279

At least it will time out after 15 minutes now.

However I did not find the root cause of this neither could reproduce it. I suspect that somehow the expected event is getting missed in some cases. We could do something like:

a. Re-requesting the events if the expected event is not received and 80% of the timeout has passed.
b. After 80% of the timeout has passed, stop waiting for the expected event and instead run the post-check function directly.

But not really sure if any of these is a good idea.
