### ISSUE TITLE
Talos cannot reinstall from ISO on an existing system

### ISSUE THREAD

**Issue by carroarmato0** [siderolabs/talos#6696]
### Description
When booting from Talos on a USB stick to re-do an installation, the system initially loads, but then it loads into the pre-existing system.

The only workaround I found is by modifying the kernel arguments of the Talos live image by adding the talos.experimental.wipe=system option and waiting for a couple of reboots for it to enter the normal live installation stage.

### Logs
None available

### Environment
Pre-existing Talos installation on /dev/sda which has been so badly configured that it's unreachable on the network and the only way to recover it is through a reinstallation.

- Talos version: v1.3.0
- Kubernetes version: not relevant
- Platform: metal

**Comment by smira** [comment]
This is by design actually - Talos never installs itself onto an existing installation. Talos should be wiped first if the reinstall is required.

Running Talos can be wiped with `talosctl reset` command. Badly broken Talos can be wiped by going into GRUB and adding `talos.experimental.wipe=system`.

**Comment by carroarmato0** [comment]
@smira thanks for the confirmation!
