### ISSUE TITLE
include standard CNI plugins into the base Talos image

### ISSUE THREAD

**Issue by smira** [siderolabs/talos#6729]
This will make Talos more compatible with kubeadm-based node.

E.g. Flannel default manifest assumes that standard CNI plugins are already in /opt/cni/bin.

**Comment by smira** [comment]
Concern is that all standard CNI plugins are ~40 MiB compressed, and that will increase Talos `initramfs` size a lot, including memory usage.

**Comment by intersectRaven** [comment]
Maybe just add to the documentation common pain points that should be changed before applying the CNI's yamls? Calico already dictates so when the pod network is not the same to their defaults that one should modify the custom-resources.yaml before applying.

**Comment by smira** [comment]
I believe Calico, Cilium ship with the full set of CNI plugins they need and put them on the host filesystem automatically.

**Comment by intersectRaven** [comment]
Yes, I just used it as an example of things that other CNIs already indicate to take note of and modify before applying. For Flannel, I encountered before the issue of the loopback plugin missing since, as you indicated in the OP, it assumes the plugin is at a specific directory. Talos has it in a different directory so it would've been better if that directory was indicated somewhere rather than someone like myself having to delve into the source to find where I should redirect or the change necessary to make the updated yaml to work.

**Comment by smira** [comment]
See also: https://github.com/containerd/containerd/issues/8006

**Comment by utkuozdemir** [comment]
After a discussion with @smira, we have decided to not include the plugins in the base image. It grows initramfs size significantly (around ~10MB compressed) with the 4 required plugins for flannel upstream. As most other CNIs bring the required plugins with them, it is not worth to grow initramfs size just for flannel. Most users who want to use a custom CNI go with something than flannel anyway to get NetworkPolicies support.
