### ISSUE TITLE
Docs use /latest/ by default instead of version

### ISSUE THREAD

**Issue by caraar12345** [siderolabs/talos#7146]
### Description

All the links to talos.dev docs from Google have been indexed under `https://www.talos.dev/v1.3/` so all documentation linked from Google comes up with a header callout:

> Version v1.3 of the documentation is no longer actively maintained. The site that you are currently viewing is an archived snapshot. For up-to-date documentation, see the [latest version](https://www.talos.dev/v1.4/introduction/getting-started/).

Would you consider setting the latest version to `https://www.talos.dev/latest/` rather than `https://www.talos.dev/v1.4/` by default? That way, indexed links don't rot every time you release a new version!

**Comment by smira** [comment]
thanks for bringing this up, we need to kick some process to update things. @rsmitty I think you know this thing

**Comment by steverfrancis** [comment]
Google has been told to index the new pages, but it does take it a while. 
But if, as is the suggestion, the current docs are always under `/latest/` , as opposed to that redirecting to `/1.4/` etc that would solve the issue of stale results.
@rsmitty can tell us if that is possible, perhaps...

**Comment by rsmitty** [comment]
Yeah, I think that the way it's configured is that google should reindex our site like once a week or so. And when that happens, we have code in place to point to the latest released version so that should be what's indexed and shows in search results. There can be a little drag between a new docs release and when the scrape happens though, I suppose.

**Comment by steverfrancis** [comment]
Currently:
we release 1.4, so google has to read the 1.4 docs, and the 1.3 docs, to see that /1.3/getting-started now has  a canonical pointer to /1.4/getting-started. Google will, after that, update and point to the correct thing, but before that it will deliver people to the /1.3/ stale docs.

If its possible to have /latest/ be a symlink to the latest, then:
We release 1.4, and update the /latest/ symlink to point to the 1.4 tree.
Google still has to crawl /latest/getting-started to index the new content that is in 1.4 versus 1.3 (if any), but if /latest/ is always the canonical in google's index, it will never point people to old versions of the documentation.

And we cant control when google crawls the 1.3 and 1.4 doc trees, to see the new canonical links. Just suggest to google that it does so.

We still would need a recrawl to cover page moves, and for new content in pages to be indexed, but the search results would never go to an old version. (Most pages do not get updated from release to release, so this isn't a big deal, but the user experience is nicer if they go to the current tree.)

**Comment by rsmitty** [comment]
Makes sense. We'll have to see what's possible within the framework.

**Comment by Jackbennett** [comment]
Indexing `/latest/` misses out search results for a thing that's no longer mentioned on newer docs because it's obsolete. The user comes from a search result to a page that doesn't have the query much less the answer anymore, at least the "see new version" button is a chance to find the docs diff and see the section removed with reasons.

I think a lot of cilium issues are about to do this as you've much-improved the setup guide from pre 1.4

I also think if you review search traffic you should know a lot of hits are going to some specific 1.1 item that perhaps hasn't been documented well enough in later page moves. This is critical on pages that list common-issues and resolutions.
