### ISSUE TITLE
KubePrism goes away under load

### ISSUE THREAD

**Issue by alexandrem** [siderolabs/talos#8112]
### Description

We've noticed that certain K8s worker nodes lose their connectivity towards the kube-apiserver through KubePrism when running under heavy load (thousands of pods during load tests).

It seems that the kubelet is not able to talk to KubePrism anymore.

### Logs

```
# NOTE only kept the bare metal machines in this output
$ k get nodes                                          
NAME                                 STATUS     ROLES           AGE   VERSION
talos-0qj-rku                        Ready      <none>          21h   v1.26.11
talos-0uz-2wc                        Ready      <none>          21h   v1.26.11
talos-282-nnw                        Ready      <none>          21h   v1.26.11
talos-316-05w                        Ready      <none>          21h   v1.26.11
talos-3dl-buq                        Ready      <none>          21h   v1.26.11
talos-41w-n9m                        Ready      <none>          21h   v1.26.11
talos-5b9-zy0                        NotReady   <none>          20h   v1.26.11
talos-5is-v65                        Ready      <none>          21h   v1.26.11
talos-5nb-8jg                        NotReady   <none>          21h   v1.26.11
talos-7x6-yx4                        NotReady   <none>          21h   v1.26.11
talos-8fd-pea                        Ready      <none>          21h   v1.26.11
talos-9sq-e1t                        Ready      <none>          21h   v1.26.11
talos-a61-2e4                        Ready      <none>          20h   v1.26.11
talos-ae4-qig                        Ready      <none>          20h   v1.26.11
talos-bq7-4vg                        Ready      <none>          21h   v1.26.11
talos-cgj-3lk                        Ready      <none>          21h   v1.26.11
talos-es0-6rn                        Ready      <none>          20h   v1.26.11
talos-gq0-voj                        Ready      <none>          20h   v1.26.11
talos-k2s-v5t                        Ready      <none>          21h   v1.26.11
talos-kr3-413                        Ready      <none>          21h   v1.26.11
talos-pre-wy5                        Ready      <none>          21h   v1.26.11
talos-qnh-9n4                        Ready      <none>          21h   v1.26.11
talos-r70-odn                        Ready      <none>          20h   v1.26.11
talos-tw0-rk6                        Ready      <none>          20h   v1.26.11
talos-v38-xvz                        Ready      <none>          21h   v1.26.11
talos-waa-xp7                        Ready      <none>          18h   v1.26.11
talos-wui-eek                        Ready      <none>          21h   v1.26.11
talos-y80-mly                        Ready      <none>          20h   v1.26.11
talos-yo4-96w                        Ready      <none>          21h   v1.26.11
```

```
$ talosctl -n talos-5b9-zy0 logs kubelet --tail=10     
130.x.x.x: {"ts":1703278002302.1658,"caller":"server/server.go:299","msg":"Unable to authenticate the request due to an error","err":"Post \"https://localhost:7445/apis/authentication.k8s.io/v1/tokenreviews\": dial tcp [::1]:7445: connect: connection refused","errCauses":[{"error":"Post \"https://localhost:7445/apis/authentication.k8s.io/v1/tokenreviews\": dial tcp [::1]:7445: connect: connection refused"}]}
130.x.x.x: {"ts":1703278004210.1064,"caller":"lease/controller.go:146","msg":"failed to ensure lease exists, will retry in 7s, error: Get \"https://localhost:7445/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/talos-5b9-zy0?timeout=10s\": dial tcp [::1]:7445: connect: connection refused\n"}
130.x.x.x: {"ts":1703278008315.8704,"caller":"kubelet/kubelet_node_status.go:70","msg":"Attempting to register node","v":0,"node":{"name":"talos-5b9-zy0"}}
130.x.x.x: {"ts":1703278008316.8691,"caller":"kubelet/kubelet_node_status.go:92","msg":"Unable to register node with API server","node":{"name":"talos-5b9-zy0"},"err":"Post \"https://localhost:7445/api/v1/nodes\": dial tcp [::1]:7445: connect: connection refused"}
130.x.x.x: {"ts":1703278010516.1116,"caller":"webhook/webhook.go:154","msg":"Failed to make webhook authenticator request: Post \"https://localhost:7445/apis/authentication.k8s.io/v1/tokenreviews\": dial tcp [::1]:7445: connect: connection refused\n"}
130.x.x.x: {"ts":1703278010516.1943,"caller":"server/server.go:299","msg":"Unable to authenticate the request due to an error","err":"Post \"https://localhost:7445/apis/authentication.k8s.io/v1/tokenreviews\": dial tcp [::1]:7445: connect: connection refused","errCauses":[{"error":"Post \"https://localhost:7445/apis/authentication.k8s.io/v1/tokenreviews\": dial tcp [::1]:7445: connect: connection refused"}]}
130.x.x.x: {"ts":1703278010846.4963,"caller":"eviction/eviction_manager.go:261","msg":"Eviction manager: failed to get summary stats","err":"failed to get node info: node \"talos-5b9-zy0\" not found"}
130.x.x.x: {"ts":1703278011212.1487,"caller":"lease/controller.go:146","msg":"failed to ensure lease exists, will retry in 7s, error: Get \"https://localhost:7445/apis/coordination.k8s.io/v1/namespaces/kube-node-lease/leases/talos-5b9-zy0?timeout=10s\": dial tcp [::1]:7445: connect: connection refused\n"}
130.x.x.x: {"ts":1703278011467.3022,"caller":"webhook/webhook.go:154","msg":"Failed to make webhook authenticator request: Post \"https://localhost:7445/apis/authentication.k8s.io/v1/tokenreviews\": dial tcp [::1]:7445: connect: connection refused\n"}
130.x.x.x: {"ts":1703278011467.3687,"caller":"server/server.go:299","msg":"Unable to authenticate the request due to an error","err":"Post \"https://localhost:7445/apis/authentication.k8s.io/v1/tokenreviews\": dial tcp [::1]:7445: connect: connection refused","errCauses":[{"error":"Post \"https://localhost:7445/apis/authentication.k8s.io/v1/tokenreviews\": dial tcp [::1]:7445: connect: connection refused"}]}
```

```
$ talosctl -n talos-5b9-zy0 get kubeprismstatus -o yaml
WARNING: 130.x.x.x: server version 1.5.5 is older than client version 1.6.0
node: talos-5b9-zy0
metadata:
    namespace: k8s
    type: KubePrismStatuses.kubernetes.talos.dev
    id: k8s-loadbalancer
    version: 2
    owner: k8s.KubePrismController
    phase: running
    created: 2023-12-15T18:17:45Z
    updated: 2023-12-15T18:17:50Z
spec:
    host: localhost:7445
    healthy: true
```

```
talosctl -n talos-5b9-zy0 netstat | grep 7445
# no output
```

### Environment

- Talos version: v1.5.5
- Kubernetes version: v1.26.11
- Platform:

**Comment by smira** [comment]
Can you get the `talosctl support` for this node please?

**Comment by maxheyer** [comment]
I think we also had issues related to this. Changing the qps for the kube-api and cilium fixed the problem.
However, if you set it too high, the control-plane may run out of memory.

**Comment by alexandrem** [comment]
@smira I think there might be some sensible information in the support bundle.

Is there anywhere that I can upload that privately for you to check?

**Comment by smira** [comment]
Send me DM in Slack if that works for you

**Comment by alexandrem** [comment]
@maxheyer We tuned some Cilium settings a few weeks ago, but it didn't seem to help.

What settings did you set specifically?

**Comment by maxheyer** [comment]
@alexandrem 

```
k8s-client-burst: 100
k8s-client-qps: 50
k8sClientRateLimit:
  burst: 100
  qps: 50
```

**Comment by smira** [comment]
@alexandrem the first clear issue here is that discovery service is disabled, and KubePrism doesn't work in this scenario as it should - it doesn't receive properly addresses of the controlplane nodes. (see also #8143). Discovery Service discovery shouldn't be disabled (it is enabled by default).

Still looking into the connection refused errors though.

**Comment by smira** [comment]
you shouldn't have this:

```yaml
cluster:
    discovery:
            service:
                disabled: true
```

It's better to leave the `cluster.discovery` settings as defaults. With #8143 fixed, it'd be a bit better, but relying on Kubernetes to configure access to Kubernetes is not going to be bullet-proof. Right now KubePrism for you doesn't work, as it always talks to the upstream. Let's see how it performs with Talos 1.6.2 (once it is released) and discovery service enabled.

**Comment by smira** [comment]
Talos 1.6.2 was released with fixes, if the problem doesn't go away, please re-open.

**Comment by zargony** [comment]
FYI changes in #8151 broke my home lab cluster. I'm running IPv6 first, i.e. node IPs, pod subnets and service subnets are set to have IPv6 first and IPv4 addresses second. This makes k8s choose IPv6 as the primary address (similar to an IPv6-only cluster) and only services that specify DualStack are getting a legacy IPv4 as a second address. `kubernetes.default.svc` resolves to the IPv6 service IP and the cluster became unhealthy and stopped responding because nodes tried to reach their apiserver via `[fdxx:xxxx::xx]:7445`, which was not reachable anymore. Other processes tried to reach 127.0.0.1:7445 instead, which also didn't work since the apiserver certificate did not contain a SAN entry for 127.0.0.1.

In the end, I ended up disabling KubePrism (which also wasn't as simple as editing machineconfig, because kubeconfig-in-cluster needs to be updated manually afterwards)

I wasn't aware that KubePrism doesn't support IPv6. Imho it shouldn't be enabled by default if it doesn't support IPv6 since Talos Linux doesn't work out-of-the-box anymore if you don't have primary IPv4 (and many cloud providers started to charge extra for IPv4 addresses recently, so I suppose IPv6-only will get more popular over time)

**Comment by smira** [comment]
@zargony how is it related to IPv6?

The change was to use 127.0.0.1 explicitly, and the thing is that you need to make sure you update controlplanes first so that they include 127.0.0.1 in apiserver certSANs. Upgrading controlplanes first is always the recommendation with Talos.

**Comment by zargony** [comment]
@smira Oops sorry, I probably posted to the wrong issue. In 1.6.0 and 1.6.1, KubePrism worked fine for me. Upgrading to 1.6.2, cluster became unhealthy and dmesg started to show `connection refused` errors to `[fdxx:xxxx::1]:7445` (which is `kubernetes.default.svc`). I think this is related to KubePrism not supporting IPv6, but probably not this issue about changing `localhost` to `127.0.0.1`. However, I think that hardcoding `127.0.0.1` (or enabling KubePrism) will lead to problems on systems without IPv4, so having it enabled by default doesn't feel good somehow. (But that's just my opinion. Maybe at least a more visible warning / documentation would be helpful to make people aware that default configuration doesn't work without IPv4. I completely missed it until running into problems)

As for the certSANs, I upgraded the control plane to 1.6.2 first as recommended. I then noticed failed connections to 127.0.0.1:7445 because of missing SAN for 127.0.0.1. Unfortunately I didn't capture the details as I was busy with recovering the control plane. Now that it's available again, the cert shows SANs for all names and IPs, including 127.0.0.1 (but not ::1 btw)

**Comment by smira** [comment]
@zargony I don't think you can _disable_ IPv4 with Talos and have it still working. You might not have IPv4 connectivity, but that's fine. 

On upgrade to 1.6.2 just update controlplane first as recommended always, and then upgrade workers. CertSAN issue will be sorted out automatically, might need a couple more minutes for HA clusters.
