### ISSUE TITLE
metal-amd64.iso from v1.6.6 release shows v1.5.5

### ISSUE THREAD

**Issue by skystar-p** [siderolabs/talos#8427]
### Description

I'm new to Talos Linux and just tried to install the latest release (v.1.6.6). But it shows v1.5.5 on the dashboard and seems using v1.5.5 installer at install phase.

Downloaded iso from:
https://github.com/siderolabs/talos/releases/tag/v1.6.6

### Logs

No logs, but screenshot attached.
![screenshot](https://github.com/siderolabs/talos/assets/1418874/8cfeb485-f977-4937-8f8b-f0071e93d270)

checksum of image:
```
> sha256sum metal-amd64.iso
177e17b1f95f8122b09f61163b0c1682990086c0a53ed03ed5c34dbf92e5841a  metal-amd64.iso
```

### Environment

- Talos version: N/A
- Kubernetes version: N/A
- Platform: Proxmox

**Comment by smira** [comment]
The actual version installed when booting via an ISO is actually set by the `machine.install.image` in the machine configuration of Talos, not by the version of the ISO.

If you use a matching version of `talosctl` for `talosctl gen config`, it would be set automatically, otherwise you'd need to patch your machine config to make it match the version you want to install.
