### ISSUE TITLE
Automatically rotate the kubelet certificates

### ISSUE THREAD

**Issue by rgl** [siderolabs/talos#8523]
## Feature Request

Automatically manage/rotate the kubelet certificates.

Not sure if this relates to:

* https://github.com/siderolabs/talos/issues/8440
* https://github.com/siderolabs/talos/issues/3817

### Description

I'm still trying to wrap my head around this kubelet certificate rotation problem, so please bear with me.

From what I understood, the kubelet must use a certificate signed by the k8s cluster CA, so that its clients (e.g. metrics-server) can establish a trusted connection (because, somehow, they are configured to trust the k8s cluster CA), correct?

By reading the documentation at https://kubernetes.io/docs/reference/access-authn-authz/kubelet-tls-bootstrapping/#approval it seems kube-controller-manager can be configured to automatically sign the kubelet CSR.

If so, why isn't Talos configured like this automatically (i.e. automatic kubelet certificate rotation)? Why do we need to install extra controllers (e.g. talos-cloud-controller-manager or alex1989hu/kubelet-serving-cert-approver) or extra configurations for that?

**Comment by arcker** [comment]
Hi @rgl 

to start I love your repos @rgl i often use them as starting/bootstrap.

I had the same exact problem for few days trying different "bootstrap" talos repos.

they all have this csr approve with the rotate-server-certificates: true

the bootstrap from @onedr0p https://github.com/onedr0p/cluster-template uses it too.

when I don't set this option, all is fine, certificates are well delivered. but I wonder for their expiration.

so for now i let those "auto approvers" deployed with this option, otherwise they are never deployed automatically.

**Comment by smira** [comment]
The Kubernetes docs above have nothing to do with server kubelet certificates, they are about client kubelet certificates. So let's not confuse these two unrelated things.

By default, kubelet uses self-signed server certificate, which doesn't need any kind approvers. So the metrics-server is the issue here, Talos sets up client cert auto-approve, but Kubernetes by design never approves server certs, and it's not something we can do

**Comment by smira** [comment]
So to make it clear - at some point in the future Talos might support automatic server/client kubelet certificates, but the problem/solution in this ticket is not applicable.
