### ISSUE TITLE
There isn't clear documentation with creating a custom talos ISO with custom drivers

### ISSUE THREAD

**Issue by DavidIlie** [siderolabs/talos#8594]
In basic terms, I have a setup of virtual machines composing my Talos cluster. For my worker nodes, I have been trying to figure out how to modify the `nonfree-kmod-nvidia` driver to contain a different .run file for my grid vGPUs and I have spent over 5 hours trying to compile the linux kernel in the (https://github.com/siderolabs/pkgs)[packages repo] but haven't gotten anywhere from here.

Is there a clear guide or could someone guide me towards this.

- I need to build a custom Talos v1.6.7 ISO which contains a different run file for the nvidia driver
- I can then specify this also in the `talconfig` so I can deploy a fresh cluster with this with the `talhelper` and (https://github.com/onedr0p/cluster-template)[cluster template]

**Comment by DavidIlie** [comment]
Or if I can build a custom extensions which contains my nvidia driver

**Comment by smira** [comment]
You'd have to be able to to lots of compile work, but follow the guide https://www.talos.dev/v1.6/advanced/customizing-the-kernel/

You'd need to build a new kernel and NVIDIA package at the same time, so that the kernel module signing key is in sync.

Then build a custom Talos with your kernel, and custom extension for NVDIA referencing your NVIDIA package. If you have more questions, please open a discussion with some details.
