### ISSUE TITLE
Talos won't connect to Omni without system information

### ISSUE THREAD

**Issue by rothgar** [siderolabs/talos#8647]
## Bug Report
When trying to connect to an Omni endpoint the connection is not established until the system is able to gather information.
https://github.com/siderolabs/talos/blob/main/pkg/machinery/resources/hardware/system_information.go#L28-L35

We should have a way to set/override this information dynamically if the underlying hypervisor or environment doesn't provide the needed details.

This is also related to #8646 because we saw the problem on Oxide instances but it could be applied generically for any system that doesn't return information.

### Description
We should add a provider for Oxide but we also should think of a way to generically solve this problem. Either with kernel parameters to specify the information or a way for Talos to skip needing this information and having Omni automatically generate a UUID if not provided.

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
- Kubernetes version: [`kubectl version --short`]
- Platform: Oxide

**Comment by smira** [comment]
This is by design, as Talos has to identify itself before establishing SideroLink connection. Proper question from my point of view is:

- if Oxide supports SMBIOS info, problem goes away without any changes on our side
- if Oxide supports some other source of information to get unique instance ID, we could use that.

But the fact that Talos doesn't establish SideroLink connection without instance ID is not an issue on its own.

**Comment by rothgar** [comment]
Oxide added SMBIOS information to their hypervisor and this is working now
