### ISSUE TITLE
SAN Certificates for machine not updating

### ISSUE THREAD

**Issue by danielheimburg** [siderolabs/talos#9008]
## Bug Report
I'm trying to deploy kube-metrics-server over SSL and getting errors about ips and hostnames of the nodes are not in the certificate for kubelet on all nodes. I can verify this with running 'openssl s_client -showcerts -connect <node>:10250 < /dev/null | openssl x509 -text -noout' which returns a SAN with "DNS:<hostname>" only.

From what I can find in the documentation it seems like I can set SAN-names with 'machine.certSANs' however when I've done this the certificate from kubelet does not change. I've also tried to reboot the host but nothing changes.

Am I misunderstanding this or how can I get encryption for kubelet?

### Environment

- Talos version: v1.7.4
- Kubernetes version: v1.30.1
- Platform:

**Comment by smira** [comment]
The config option `.machine.certSANs` has nothing to do with `kubelet` API on port 10250. In fact, Talos doesn't manage kubelet PKI, it only assists kubelet in some simple ways, so that part of the configuration if on the kubelet side.

I guess your question is answered in the [docs](https://www.talos.dev/v1.7/kubernetes-guides/configuration/deploy-metrics-server/).
