### ISSUE TITLE
Longhorn storage | Latest Kernel is missing NFS settings

### ISSUE THREAD

**Issue by dimidevops** [siderolabs/talos#9411]
### Description
After upgrading Longhorn from 1.6.2 to 1.7.1 and Talos from 1.7.5 to 1.7.7, longhorn is reporting that NFS kernel config settings are missing from the latest kernel 6.6.52-talos.
### Logs
![Screenshot 2024-10-01 131643](https://github.com/user-attachments/assets/f208c68c-4097-4007-adee-99f4332fca12)

![image](https://github.com/user-attachments/assets/ab6531fb-722e-4d55-972a-c618542ddb18)

### Environment

- Talos version: [`talosctl version --nodes <problematic nodes>`]
 Client:
        Tag:         v1.7.7
        SHA:         68794084
        Built:
        Go version:  go1.22.7
        OS/Arch:     linux/amd64
Server:
        NODE:        infra-01
        Tag:         v1.7.7
        SHA:         68794084
        Built:
        Go version:  go1.22.7
        OS/Arch:     linux/amd64
        Enabled:     RBAC

- Kubernetes version: [`kubectl version --short`]
    Client Version: v1.30.3
    Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
    Server Version: v1.30.5
- Platform: 
    Proxmox

**Comment by smira** [comment]
The error is totally unrelated, Talos doesn't have kernel config in `/boot` directory, so the root cause is something else, and Longhorn tried to be smart to do a detection of common problems.

Talos actual kernel config can be read with `talosctl cat /proc/config.gz | zless`

I don't know exactly what the problem is, you might ask Longhorn or dig through their logs.

**Comment by dimidevops** [comment]
You are right, their kernel config check script in the latest Longhorn release is not "optimized" to check on the correct location for Talos OS
