### ISSUE TITLE
zstd compressed initramfs file is named initramfs.xz

### ISSUE THREAD

**Issue by jnohlgard** [siderolabs/talos#9532]
### Description

The initramfs file is compressed with Zstd compression but is named initramfs.xz in the boot partition.

### Environment

- Talos version: v1.8.0
- Kubernetes version: N/A
- Platform: metal

**Comment by smira** [comment]
Yes, naming is hard. 

`initramfs.xz` is a historical name for one of the main assets of Talos Linux (with the kernel asset), and it was indeed xz-compressed, but also it can be a concatenation of multiple images, some of them would be compressed, some not, so the name was wrong even before zstd.

Changing that name is a bit hard due to many dependencies across different versions, but proper name should be just `initramfs` without any compression-specific extension. 

So for now we'll keep it until we have a reason to change.

In the UEFI/UKI world we're moving towards, there's no user-visible file like that, so it becomes a non-issue.
